In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('gym_members_exercise_tracking.csv')
df.head()

,age,gender,weight_kg,height_m,max_bpm,avg_bpm,resting_bpm,session_duartion_h,calories_burned,workout_type,fat_pct,water_intake_l,workout_frequency_dpw,experience_level,bmi
0,56,Male,88.3,1.71,180,157,60,1.69,1313,yoga,12.6,3.5,4,3,30.20
1,46,Female,74.9,1.53,179,151,66,1.30,883,hiit,33.9,2.1,4,2,32.00
2,32,Female,68.1,1.66,167,122,54,1.11,677,cardio,33.4,2.3,4,2,24.71
3,25,Male,53.2,1.70,190,164,56,0.59,532,strength,28.8,2.1,3,1,18.41
4,38,Male,46.1,1.79,188,158,68,0.64,556,strength,29.2,2.8,3,1,14.39

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    973 non-null    int64
 1   gender                 973 non-null    object
 2   weight_kg              973 non-null    float64
 3   height_m               973 non-null    float64
 4   max_bpm                973 non-null    int64
 5   avg_bpm                973 non-null    int64
 6   resting_bpm            973 non-null    int64
 7   session_duartion_h     973 non-null    float64
 8   calories_burned        973 non-null    int64
 9   workout_type           973 non-null    object
 10  fat_pct                973 non-null    float64
 11  water_intake_l         973 non-null    float64
 12  workout_frequency_dpw  973 non-null    int64
 13  experience_level       973 non-null    int64
 14  bmi                    973 non-null    float64
dtypes: float64(6), int64(7), object(2)
memory usage: 114.2+ KB

In [4]:
df.gender.value_counts()

gender
Male      511
Female    462
Name: count, dtype: int64

In [5]:
wrangled_df = df.rename(columns = {'gender':'is_male'})
wrangled_df.is_male = (wrangled_df.is_male == 'Male').astype(int)
wrangled_df.is_male.value_counts()

is_male
1    511
0    462
Name: count, dtype: int64

In [6]:
wrangled_df.head()

,age,is_male,weight_kg,height_m,max_bpm,avg_bpm,resting_bpm,session_duartion_h,calories_burned,workout_type,fat_pct,water_intake_l,workout_frequency_dpw,experience_level,bmi
0,56,1,88.3,1.71,180,157,60,1.69,1313,yoga,12.6,3.5,4,3,30.20
1,46,0,74.9,1.53,179,151,66,1.30,883,hiit,33.9,2.1,4,2,32.00
2,32,0,68.1,1.66,167,122,54,1.11,677,cardio,33.4,2.3,4,2,24.71
3,25,1,53.2,1.70,190,164,56,0.59,532,strength,28.8,2.1,3,1,18.41
4,38,1,46.1,1.79,188,158,68,0.64,556,strength,29.2,2.8,3,1,14.39

In [7]:
wrangled_df.to_csv('wrangled_data.csv', index = False)